### ISSUE TITLE
Crab library license

### ISSUE THREAD

**Issue by dthaler** [vbpf/ebpf-verifier#104]
My understanding is that the src/crab directory is a Derivative Work based on the https://github.com/seahorn/crab library (and [this commit](https://github.com/vbpf/ebpf-verifier/commit/1f2f8337adf6d884c86023317e642936a74da89d) among others does confirm that).
The https://github.com/seahorn/crab code [LICENSE](https://github.com/seahorn/crab/blob/master/LICENSE) is Apache 2.0 where clause 4 says:

>    4. Redistribution. You may reproduce and distribute copies of the
>       Work or Derivative Works thereof in any medium, with or without
>       modifications, and in Source or Object form, provided that You
>       meet the following conditions:
> 
>       (a) You must give any other recipients of the Work or
>           Derivative Works a copy of this License; and
> 
>       (b) You must cause any modified files to carry prominent notices
>           stating that You changed the files; and
> 
>       (c) You must retain, in the Source form of any Derivative Works
>           that You distribute, all copyright, patent, trademark, and
>           attribution notices from the Source form of the Work,
>           excluding those notices that do not pertain to any part of
>           the Derivative Works; and
> 
>       (d) If the Work includes a "NOTICE" text file as part of its
>           distribution, then any Derivative Works that You distribute must
>           include a readable copy of the attribution notices contained
>           within such NOTICE file, excluding those notices that do not
>           pertain to any part of the Derivative Works, in at least one
>           of the following places: within a NOTICE text file distributed
>           as part of the Derivative Works; within the Source form or
>           documentation, if provided along with the Derivative Works; or,
>           within a display generated by the Derivative Works, if and
>           wherever such third-party notices normally appear. The contents
>           of the NOTICE file are for informational purposes only and
>           do not modify the License. You may add Your own attribution
>           notices within Derivative Works that You distribute, alongside
>           or as an addendum to the NOTICE text from the Work, provided
>           that such additional attribution notices cannot be construed
>           as modifying the License.
> 
>       You may add Your own copyright statement to Your modifications and
>       may provide additional or different license terms and conditions
>       for use, reproduction, or distribution of Your modifications, or
>       for any such Derivative Works as a whole, provided Your use,
>       reproduction, and distribution of the Work otherwise complies with
>       the conditions stated in this License.

I didn't see anything for which parts (c) or (d) would apply but requirements (a) and (b) do apply.
(a) applies since the ebpf-verifier is otherwise under the MIT license rather than Apache (which is permitted by the last paragraph only if the Apache license is also provided for this library).

For (b), some project liberally interpret that such that a github history is considered prominent notice.   crab_utils\heap.hpp is an example of a file that does contain a prominent notice in it, but other crab files do not.

Furthermore, some parts of the Crab library in the ebpf-verifier project carry a notice like this one from src/crab/wto.hpp:

>  * Author: Arnaud J. Venet (arnaud.j.venet@nasa.gov)
>  * Contributors: Jorge A. Navas (jorge.navas@sri.com)
>  *
>  * Notices:
>  *
>  * Copyright (c) 2011 United States Government as represented by the
>  * Administrator of the National Aeronautics and Space Administration.
>  * **All Rights Reserved.**

Does "All Rights Reserved" preclude the ability to create derivative works
as the ebpf-verifier did?  Presumably Jorge as a listed contributor acquired
such right, and this should probably be stated explicitly somewhere.

Jorge should probably weigh in with his preferred resolution to these crab issues.

**Comment by dthaler** [comment]
Arie reports that Crab was derived from 
https://github.com/NASA-SW-VnV/ikos

**Comment by caballa** [comment]
Sorry I join this a bit late. Do you still need my input?

**Comment by caballa** [comment]
I'm happy with the use of `SPDX-License-Identifier`. Just one thing to fix. The implementation of the zones domain is part of Crab (Not IKOS). So the file https://github.com/vbpf/ebpf-verifier/blob/master/src/crab/split_dbm.hpp is not NASA 1.3 and it should be Apache? The file https://github.com/vbpf/ebpf-verifier/blob/master/src/crab/split_dbm.cpp is MIT, should it be Apache?

**Comment by dthaler** [comment]
@caballa Can you generate a pull request with your proposed fixes?  And also propose a resolution to the license points, especially point (b) above?

**Comment by dthaler** [comment]
@caballa there is still a remaining question for you on this issue.  Specifically the Crab license (Apache 2.0) clause 4(b) says:

> (b) You must cause any modified files to carry prominent notices
> stating that You changed the files;

And currently the Preval code base contains modified versions of Crab files (the ones in Prevail that now have Apache-2.0 as the SPDX id at the top), so the Crab imposes the above requirement on Prevail.   There are two approaches we know of that are common in the open source world.

One is to explicitly have a note in the comments at the top of each modified file.
Another is to agree that the git log is sufficient.

The second one is lighter weight, and if you (as the Crab author) agree that is sufficient, then I think we can now close this issue.  This would be my preference if you agree.  If you instead want to see comments at the top of each modified file, we would need another pull request to add such notices.

**Comment by caballa** [comment]
Git log is sufficient.

**Comment by dthaler** [comment]
> Git log is sufficient.

Thanks for confirming.  I believe that this issue can now be closed.
