### ISSUE TITLE
Support verifying tail calls

### ISSUE THREAD

**Issue by dthaler** [vbpf/ebpf-verifier#117]
On PR #115, Elazar wrote:

> As far as I understand, the issue is that we do not support more than one argument to the program, which seems to be needed for a tail-called function (=program) such as this one. Prevail has no special treatment for tail calls, other than analyzing the dedicated no-return function call at the call site.
> 
> The program comes from the same object file that contains the only "real" failure we had - compiled (probably) from some version of this file: xdp_ddos01_blacklist_kern.c. Presumably the non-inline function parse_port(ctx, proto, hdr), tail-called from here, which accepts more than one argument. Prevail does not support that, though it should be simple, unlike analyzing function calls in regular code.
> 
> See the second instruction - it tests for r2, the register holding the parameter proto.
> 
>```
> $ ./check ebpf-samples/prototype-kernel/xdp_ddos01_blacklist_kern.o .text --asm=/dev/stdout
>        0:       r1 = *(u32 *)(r1 + 4)
>        1:       if r2 == 6 goto +8 <10>
>        2:       r6 = 2
>        3:       if r2 != 17 goto +44 <48>
>        4:       r7 = 1
>        5:       r6 = 0
>        6:       r2 = r3
>        7:       r2 += 8
>        8:       if r2 > r1 goto +39 <48>
>        9:       goto +5 <15>
>       10:       r7 = 0
>       11:       r2 = r3
>       12:       r2 += 20
>       13:       r6 = 0
>       14:       if r2 > r1 goto +33 <48>
>       15:       r1 = *(u16 *)(r3 + 2)
>       16:       r1 = be16 r1
>       17:       *(u32 *)(r10 - 4) = r1
>       18:       r2 = r10
>       19:       r2 += -4
>       20:       r1 = map_fd 65792
>       22:       r0 = map_lookup_elem:1(r1:FD, r2:K)
>       23:       r6 = 2
>       24:       if r0 == 0 goto +23 <48>
>       25:       r1 = 1
>       26:       r1 <<= r7
>       27:       r2 = *(u32 *)(r0 + 0)
>       28:       r2 &= r1
>       29:       r6 = 2
>       30:       if r2 == 0 goto +17 <48>
>       31:       r2 = map_fd 131328
>       33:       if r7 == 0 goto +1 <35>
>       34:       r2 = 0
>       35:       r1 = map_fd 131328
>       37:       if r7 != 0 goto +1 <39>
>       38:       r1 = r2
>       39:       r6 = 1
>       40:       if r1 == 0 goto +7 <48>
>       41:       r2 = r10
>       42:       r2 += -4
>       43:       r0 = map_lookup_elem:1(r1:FD, r2:K)
>       44:       if r0 == 0 goto +3 <48>
>       45:       r1 = *(u32 *)(r0 + 0)
>       46:       r1 += 1
>       47:       *(u32 *)(r0 + 0) = r1
>       48:       r0 = r6
>       49:       exit
>```
> I couldn't find the call site itself, though I don't believe this matters too much, and IIRC there are indirect ways to do that.
> 
> The CI did not catch the change in test set since it only prints the results of the tests, without checking anything.

**Comment by dthaler** [comment]
Another issue in verifying tail calls is ensuring that the "ctx" type matches, so that you can't (say) run into the same problems outlined in issue #192 where the caller has an xdp context and tail calls a program written to assume a socket context.

Thus, I believe verifying a bpf_tail_call() operation requires either:
a)	checking that the caller and previously-verified callee have the same “ctx” type, or
b)	only accepting the bpf_tail_call() as valid if the callee passes verification using the caller’s program type

**Comment by dthaler** [comment]
Finally, another issue is that the termination checks have to take tail calls into account, to prevent (say) tail call loops.

**Comment by elazarg** [comment]
I think it's simpler to track tail call loops using the runtime rather than statically, and the overhead is negligible.

**Comment by dthaler** [comment]
@elazarg fyi this issue is now the highest priority ask for the verifier from the ebpf-for-windows project.  I don't know offhand how important it is to support multiple arguments, it might be ok to punt on that and only support one initially.  But at least the ability to verify the `bpf_tail_call()` API including the points in my first comment above from May 21:

> Another issue in verifying tail calls is ensuring that the "ctx" type matches, so that you can't (say) run into the same problems outlined in issue #192 where the caller has an xdp context and tail calls a program written to assume a socket context.
> 
> Thus, I believe verifying a bpf_tail_call() operation requires either:
> a) checking that the caller and previously-verified callee have the same “ctx” type, or
> b) only accepting the bpf_tail_call() as valid if the callee passes verification using the caller’s program type

**Comment by elazarg** [comment]
I think the runtime is responsible for not allowing any `prog_array_map` to hold programs with different type. The verifier should simply verify that this is indeed `ctx` pointer with offset 0, and that the type of the map is `PROG_ARRAY`. This addresses both (a) and (b), and I think that's how it is done in the Linux verifier and runtime. The runtime also limits the number of calls.

For easy reference:
The Linux verifier is here: https://elixir.bootlin.com/linux/v5.13.7/source/kernel/bpf/verifier.c#L12483)
The Linux runtime here: https://elixir.bootlin.com/linux/v5.13.7/source/kernel/bpf/core.c#L1554

**Comment by dthaler** [comment]
> I think the runtime is responsible for not allowing any `prog_array_map` to hold programs with different type. The verifier should simply verify that this is indeed `ctx` pointer with offset 0, and that the type of the map is `PROG_ARRAY`. This addresses both (a) and (b), and I think that's how it is done in the Linux verifier and runtime. The runtime also limits the number of calls.

By that argument, I think the verifier should not verify that the type of the map is `PROG_ARRAY` and the runtime should be responsible for checking that.  The verifier currently only understands EBPF_ARGUMENT_TYPE_PTR_TO_MAP in the prototype for bpf_tail_call.  We would have to introduce a new argument type which I now think is not needed.

**Comment by elazarg** [comment]
> > I think the runtime is responsible for not allowing any `prog_array_map` to hold programs with different type. The verifier should simply verify that this is indeed `ctx` pointer with offset 0, and that the type of the map is `PROG_ARRAY`. This addresses both (a) and (b), and I think that's how it is done in the Linux verifier and runtime. The runtime also limits the number of calls.
> 
> By that argument, I think the verifier should not verify that the type of the map is `PROG_ARRAY` and the runtime should be responsible for checking that.

That is not _exactly_ the same argument, since the checks do not happen at the same locations and the same number of times. But we can probably postpone the discussion until we have concrete examples and some data about the costs of the runtime checks versus the impact on precision.

Conceptually I think maps of pointers to programs are very different than maps of pointers to data, but that is not a strong argument.

Should I close #244 then?

**Comment by dthaler** [comment]
I reviewed 244 and I like it, so would rather see 244 merged.

**Comment by dthaler** [comment]
Closing this issue as I think it is sufficient for now.   Please reopen if you think otherwise.
