### ISSUE TITLE
Array index verification isn't strict enough?

### ISSUE THREAD

**Issue by dthaler** [vbpf/ebpf-verifier#130]
The following program passes verification:
```
int func()
{
    int foo[2];
    foo[-10] = 0;
    return 0;
}
```

The negative index should make this invalid, shouldn't it?

Verbose output follows:
```
{r10 -> [512, +oo], off10 -> [512], t10 -> [-2], r1 -> [1, 2147418112], off1 -> [0], t1 -> [-3], packet_size -> [0, 65534], meta_offset -> [-4098, 0]
 }
Numbers -> {}
0:
  r1 = 0;
  assert valid_access(r10, -48:4);
  *(u32 *)(r10 - 48) = r1;
  r0 = r1;
  goto 3;

{r10 -> [512, +oo], off10 -> [512], t10 -> [-2], r1 -> [0], S_t[-48...-45] -> [-4], t1 -> [-4], packet_size -> [0, 65534], meta_offset -> [-4098, 0], r0 -> [0], t0 -> [-4]
 off1-off0<=0, off0-off1<=0}
Numbers -> {[-48...-45]}

{r10 -> [512, +oo], off10 -> [512], t10 -> [-2], r1 -> [0], S_t[-48...-45] -> [-4], t1 -> [-4], packet_size -> [0, 65534], meta_offset -> [-4098, 0], r0 -> [0], t0 -> [-4]
 off1-off0<=0, off0-off1<=0}
Numbers -> {[-48...-45]}
3:
  assert r0 : num;
  exit;


{r10 -> [512, +oo], off10 -> [512], t10 -> [-2], r1 -> [0], S_t[-48...-45] -> [-4], t1 -> [-4], packet_size -> [0, 65534], meta_offset -> [-4098, 0], r0 -> [0], t0 -> [-4]
 off1-off0<=0, off0-off1<=0}
Numbers -> {[-48...-45]}


0 warnings
1,0.000866,4300
```

Is this expected?

**Comment by dthaler** [comment]
In contrast if the index is too _high_, it correctly fails validation:
```
 Upper bound must be lower than STACK_SIZE (valid_access(r10, 0:4))
  inv became bot after assert valid_access(r10, 0:4)
```

**Comment by elazarg** [comment]
Correct me if I'm confusing something here, but this looks like a C program with undefined behavior, that is compiled to an eBPF program with well defined and valid behavior. Of course the compiler is allowed to do that.

Can you try it with index -516 or something like that?

**Comment by dthaler** [comment]
clang will refuse to compile with index -516:
```
neg-index.c:4:15: error: Looks like the BPF stack limit of 512 bytes is exceeded. Please move large on stack variables into BPF per-cpu array map.
```

But will only generate a warning with a less severe negative index.  And often warnings are ignored by developers, especially if there's a lot of warnings and it gets lost in the noise.

Yes it's a C program with undefined behavior, but is there a way to make it fail verification?  Seems like programs with such undefined behavior should not be treated as verified.

**Comment by elazarg** [comment]
The original C program is the compiler's business, not the verifier's. If the compiler decides to generate a valid eBPF program, the verifier should not reject it (and without the original C code, it simply cannot).

You can try using indirect access to the stack, so the compiler will not use `r10` with a constant offset, which is too easy for the compiler to catch.

**Comment by caballa** [comment]
We have a similar issue with our LLVM static analyzer. If the C program has undefined behavior and it's detected by Clang then the LLVM static analyzer won't know about it. That's why we claim to analyze LLVM bitcode instead of C. 
I think here we should do the same. Our analyzer is for eBPF programs. If you choose to write the eBPF program via a C program then you need to make sure that the C program doesn't have undefined behavior (e.g., by running Clang static analyzer).

**Comment by elazarg** [comment]
Or, if you are unsure whether the program has undefined behavior, you may inspect the eBPF program to see what it does. This analysis is performed in the kernel, and is only about what the kernel cares for (in this case): safety, not correctness.
