### ISSUE TITLE
Various ebpf programs that used to pass now fail verification

### ISSUE THREAD

**Issue by dthaler** [vbpf/ebpf-verifier#134]
Many of the samples now fail, but perhaps the smallest example is:
```
./check ebpf-samples/linux/xdp_redirect_kern.o xdp_redirect
```
used to pass and now seems to fail.   Trying against various commits, the regression looks like it was introduced in the third commit of PR #125 (i.e., bad in commit 662326257570f08a1947125c6a5cf7d92caa5e0c but ok in the previous commit 3efd82a8810d442008c1bf2c802f10e6e8cf71cc).

**Comment by elazarg** [comment]
I should have inspected the test results manually. I thought that commit was low risk; obviously I was wrong.

**Comment by elazarg** [comment]
The issue is that the nondeterminization process relied on the order of the outgoing edges to decide which branch is the true branch and which is the false. This assumption had been invalidated by 662326257570f08a1947125c6a5cf7d92caa5e0c, so some branches are swapped.
