### ISSUE TITLE
Typos and grammar issues in the README file

### ISSUE THREAD

**Issue by dthaler** [vbpf/ebpf-verifier#146]
The following text in README.md is problematic:
> However, in the original source code there are redundant loads from memory to a varaible holding the same value. These were added happen due to untracked register spilling that led to false positive. Two fixes are compiled into xdp_tx_iptunnel_1_kern.o and xdp_tx_iptunnel_2_kern.o. Both pass our verifier (without any special effort) but fail the existing one:

* variable is misspelled in the first sentence
* I can't parse the second sentence
* I think "the existing one" in the last sentence above should be "the Linux kernel one"

I am not sure what was meant by the second sentence, otherwise I would generate a pull request.

**Comment by elazarg** [comment]
I think in the second sentence the word `happen` should be removed. The sentence is still awkward but hopefully it can be understood?
