### ISSUE TITLE
USE_GMP is not tested in the CI

### ISSUE THREAD

**Issue by elazarg** [vbpf/ebpf-verifier#148]
As @dthaler [pointed out](https://github.com/vbpf/ebpf-verifier/pull/145#issuecomment-754764957), PR #137 accidentally removed building with GMP from the CI.

**Comment by dthaler** [comment]
Given that it's not tested and boost is marginally faster, do we need to keep GMP support and fix this test issue or is just removing GMP an option?

**Comment by elazarg** [comment]
I don't think we need it (and we can return to it at any time if we want). @caballa what do you think?

**Comment by caballa** [comment]
I agree, no need to keep it.
