### ISSUE TITLE
NASA license is problematic for some uses

### ISSUE THREAD

**Issue by dthaler** [vbpf/ebpf-verifier#149]
The NASA 1.3 license contains copyleft-style provisions; it is not treated as a free software license by the FSF and has been essentially blacklisted in certain places, like Debian. 

For example, https://www.gnu.org/licenses/license-list.html#NASA says:

> The following licenses do not qualify as free software licenses. A nonfree license is automatically incompatible with the GNU GPL.
...
> The NASA Open Source Agreement, version 1.3, is not a free software license because it includes a provision requiring changes to be your “original creation”. Free software development depends on combining code from third parties, and the NASA license doesn't permit this.
> 
> We urge you not to use this license. In addition, if you are a United States citizen, please write to NASA and call for the use of a truly free software license.

There are currently four NASA-1.3 licensed files:

- [x] src/crab/linear_constraints.hpp
- [x] src/crab/wto.hpp
- [X] src/crab_utils/bignums_gmp.hpp
- [x] src/crab_utils/patricia_trees.hpp

bignums_gmp.hpp is fine because it's not used by default now that we have Boost as an alternative.
The other three files would still need viable replacements for ebpf-verifier to be more widely usable.

**Comment by caballa** [comment]
`linear_constraints.hpp` is a simple representation for linear expressions/constraints which can be easily re-implemented and even improved.

The other two `wto.hpp` and `patricia_trees.hpp` can take more time to re-implement but their algorithms are fully described in these two papers:

- "Efficient chaotic iteration strategies with widenings" by Bourdoncle 1993
- "Fast Mergeable Integer Maps" by Okasaki and Gill 1998
