### ISSUE TITLE
Exposing kernel pointers to user mode apps

### ISSUE THREAD

**Issue by dthaler** [vbpf/ebpf-verifier#170]
The following program passes the verifier:
```
int func(struct ctx* ctx)
{
    uint32_t key = 0;
    return bpf_map_update_elem(&map, &key, &ctx, 0);
}
```

As a result, the ctx pointer (or a pointer into the stack, etc.) can be stored in a map.
Issue is that can expose kernel addressing details to user mode apps.
The verifier does fail code that tries to use a value returned from bpf_map_lookup_elem as a pointer, so that part is fine, but it also means there's little legitimate reason to store a pointer in a map value since once there it's not a  safe pointer.

Is there any reason this should be allowed?  Seems like the verifier should fail code like above.

**Comment by elazarg** [comment]
It should fail; this looks like a serious bug to me. Can you add the `.o` file to [ebpf-samples](../../ebpf-samples)?

**Comment by dthaler** [comment]
> It should fail; this looks like a serious bug to me. Can you add the `.o` file to [ebpf-samples](../../ebpf-samples)?

Done: https://github.com/vbpf/ebpf-samples/pull/3

And working on adding it to a test case: https://github.com/vbpf/ebpf-verifier/pull/171
