### ISSUE TITLE
Test examples from ebpf-verifier-flops

### ISSUE THREAD

**Issue by ryzhyk** [vbpf/ebpf-verifier#18]
There are a total of 4 examples in the ebpf-verifier-flops directory now. We may want to try them soonish and give William some feedback.

**Comment by elazarg** [comment]
The folder [flops/](https://github.com/elazarg/ubpf/tree/master/samples/flops) contains raw test samples. Seems like mostly indirect implications of memory accesses, but I will know better after I will check it with the memory domain.

**Comment by elazarg** [comment]
Will not happen.
