### ISSUE TITLE
Verifier permits null pointer dereference after map lookup

### ISSUE THREAD

**Issue by dthaler** [vbpf/ebpf-verifier#183]
`bpf_map_lookup_elem` returns:
```
.return_type = EbpfHelperReturnType::PTR_TO_MAP_VALUE_OR_NULL,
```

However, `PTR_TO_MAP_VALUE_OR_NULL` seems to be interpreted as ignoring the "OR_NULL" part.

Verifier output:
```
Preconditions : {r10.value=[512, +oo], r10.offset=[512], r10.type=stack_pointer, r1.value=[65792], r1.type=map_fd, packet_size=[0, 65534], meta_offset=[-4098, 0], r6.value=[1], r6.type=number, S.type[-4...-1]=number, r2.offset=[508], r2.type=stack_pointer
 }
Stack: Numbers -> {[-4...-1]}
6:
  assert r1 is map_fd;
  assert r2 is stack_or_packet;
  assert within stack(r2:key_size(r1));
  r0 = map_lookup_elem:1(r1:FD, r2:K);
  goto 7;

Postconditions: {r10.value=[512, +oo], r10.offset=[512], r10.type=stack_pointer, map_value_size=[4], r0.type=map_value_of_size(4), packet_size=[0, 65534], meta_offset=[-4098, 0], r6.value=[1], r6.type=number, S.type[-4...-1]=number, r0.offset=[0], r0.value=[0, 2147418112], map_key_size=[4]
 }
```

Note the `r0.type=map_value_of_size(4)` in particular, after which an instruction to dereference the pointer is permitted.

Repro binary is in https://github.com/vbpf/ebpf-samples/pull/5

**Comment by elazarg** [comment]
The issue is not the type per-se; we can't return type of pointer-or-null, since conditions cannot change the type with the current domain (we check later that the value is not 0, but maybe it's some other number?) so the assertion should be that `r0.value != 0`. I'm not sure why this doesn't work.

**Comment by elazarg** [comment]
I thought about implementing a more sophisticated numerical domain, tracking mapping from type to value (related to a known domai-combinator named "reduced cardinal power"); with such a hypothetical domain, we'll have
`number -> 0 | pointer -> [4096, MAX_PTR]` and when we check that it is not zero, we'll get 
`number -> _|_ | pointer -> [4096, MAX_PTR]` which reduces to
`pointer -> [4096, MAX_PTR]`
