### ISSUE TITLE
probe_read disassembly shows wrong arguments

### ISSUE THREAD

**Issue by dthaler** [vbpf/ebpf-verifier#221]
Looking at the disassembly shown in issue #218 we see:

```
       5:       r0 = probe_read:4(r3, r1 is OUT[r2?])
```

The problem is that the eBPF VM requires the arguments to be in r1, r2, etc. in that order.
r3 is not the first argument.

**Comment by elazarg** [comment]
That's because [single arguments are printed before pairs of arguments](https://github.com/vbpf/ebpf-verifier/blob/master/src/asm_ostream.cpp#L186]. If I am not mistaken, items in pairs always come together so we can print them ordered nicely.

Note that this issue does not affect verification, it only matters when you are interested in the behavior.

**Comment by dthaler** [comment]
> That's because [single arguments are printed before pairs of arguments](https://github.com/vbpf/ebpf-verifier/blob/master/src/asm_ostream.cpp#L186). If I am not mistaken, items in pairs always come together so we can print them ordered nicely.
> 
> Note that this issue does not affect verification, it only matters when you are interested in the behavior.

Yep, it just caused confusion when trying to track down the root cause of #219 :)
Output like the following (from disassembly of another sample)
```
8:       r0 = sock_map_update:53(r1:CTX, r2:FD, r3:K, r4)
```
is more understandable in general since the prototypes match, in order, with what is in the source code of the eBPF program and documented in various places like [here](https://github.com/iovisor/bpf-docs/blob/master/bpf_helpers.rst).

The probe_read prototype is (from the link above):
```
int bpf_probe_read(void *dst, u32 size, const void *src)
```

so a more consistent output might be something like:
```
5:       r0 = probe_read:4(r1:OUT[r2], r2?, r3)
```

It's also a bit odd that single args use ":" whereas pairs use " is " before the type.   I would like to make them be consistent.   The ":" notation is also used at the end of the helper function name for a different meaning, to separate the symbol from its value, so maybe the ":" to separate the type vs name isn't the most consistent notation.

What about making it look slightly more C-like by putting the types first?  Maybe something like:
```
5:       r0 = probe_read:4(OUT r1[r2], r2?, r3)
8:       r0 = sock_map_update:53(CTX r1, FD r2, K r3, r4)
```

**Comment by dthaler** [comment]
Please review sample output in PR 222
