### ISSUE TITLE
can not found  radix_tree/radix_tree.hpp

### ISSUE THREAD

**Issue by LianJieZhang** [vbpf/ebpf-verifier#235]
/home/uos/ebpf-verifier/src/crab/variable.hpp:14:10: fatal error: **radix_tree/radix_tree.hpp**: 没有那个文件或目录。

```
uos@uos-PC:~/ebpf-verifier$ cat /etc/debian_version 
10.3
uos@uos-PC:~/ebpf-verifier$ dpkg -S radix_tree.hpp
r-cran-triebeard: /usr/lib/R/site-library/triebeard/include/radix/radix_tree.hpp
```

/home/uos/ebpf-verifier/src/crab/variable.hpp:14:10: fatal error: **radix_tree/radix_tree.hpp**: 没有那个文件或目录
 #include "radix_tree/radix_tree.hpp"

**Comment by elazarg** [comment]
Hi @LianJieZhang, thank you for reporting!
Did you clone the project using the flag `--recurse-submodules`? For example, like this:
```
git clone --recurse-submodules https://github.com/vbpf/ebpf-verifier.git
```

If not, run this command:
```
git submodule update --init
```

**Comment by LianJieZhang** [comment]
Oh i see, thanks！
