### ISSUE TITLE
Augment LabeledInstruction with source/file/line info from BTF if available

### ISSUE THREAD

**Issue by Alan-Jowett** [vbpf/ebpf-verifier#301]
Clang emits BTF data into the ELF file when compiling with the -g option.

This can be used to obtain the source / line / file that generated an instruction, which would make diagnosing verification failures a lot easier for developers.

I am in the process of adding a parser of BTF for this PR https://github.com/microsoft/ebpf-for-windows/pull/764, but I would be willing to move the code to this repo so that both eBPF for Windows and Prevail can benefit from it.

**Comment by elazarg** [comment]
Sure!

It is very important, and for more than debug information. There is type information there that's needed for some function signatures (it's GPL so I won't link it here).

I have also started working on it a couple of months ago, but didn't get around to finishing it: https://github.com/vbpf/ebpf-verifier/tree/new_elf. I've taken a different approach, but of course a working implementation would be much better regardless of approach :)

Do you think it would be useful to have a dedicated repository for ELF parsing?

BTW, Cillium's Golang parser is really beautifully written IMO.

**Comment by Alan-Jowett** [comment]
@dthaler mentioned in another issue that libbpf already has a BTF parser that we can probably use in place of writing our own. I will synch up with him to see if I can get more info on it.

**Comment by Alan-Jowett** [comment]
Would you be open to using [libbpf](https://github.com/libbpf/libbpf) to gather this data? It looks like [libbpf has the data](https://github.com/libbpf/libbpf/blob/fec0813359a9dd68dff7edb9f221b0f18d94433d/src/libbpf_internal.h#L414) available to it (it just doesn't have an API to expose it).

I think it would make more sense to extend libbpf to emit the data than rewrite out own parser.

**Comment by elazarg** [comment]
I agree, assuming there are no license issues.

**Comment by Alan-Jowett** [comment]
It appears to be dual-licensed:
https://github.com/libbpf/libbpf/blob/196da61f1de022671c9360f0d92d8ac49be3353a/LICENSE#L1

Is BSD-2-Clause compatible?

**Comment by elazarg** [comment]
[I think it is](https://opensource.stackexchange.com/a/582):
> The practical differences between the 2-clause BSD license and the MIT license are marginal.

But I Am Not A Lawyer.

**Comment by Alan-Jowett** [comment]
For now, I am adding this based on my own BTF parser. If / when we get the right support from libbpf we can consider switching.

**Comment by dthaler** [comment]
> For now, I am adding this based on my own BTF parser. If / when we get the right support from libbpf we can consider switching.

I think that's good, don't block on libbpf just switch to it when available.
