### ISSUE TITLE
Grant coverals.io permission to post status updates on PRs

### ISSUE THREAD

**Issue by Alan-Jowett** [vbpf/ebpf-verifier#345]
![image](https://user-images.githubusercontent.com/20480683/169368340-a092e80e-e4f8-4cf4-9e0a-901b51d3ab37.png)

I propose that we enable pull request alerts on the coverals.io page for this repo so that it can post to PRs with the code coverage status from a PR.

**Comment by elazarg** [comment]
It should work now.
