### ISSUE TITLE
btf_parse_line_information should reject BTF section if line_info_record_size == 0

### ISSUE THREAD

**Issue by Alan-Jowett** [vbpf/ebpf-verifier#365]
btf_parse_line_information should reject BTF line info data if line_info_record_size  < sizeof(bpf_line_info_t).

**Comment by Alan-Jowett** [comment]
@Alan-Jowett to provide PR to fix this.

Sample ELF file with bad BTF section that causes the problem:
[timeout-0a4aa25126bf1edb3809bd6abf86616d81e2b2dc.zip](https://github.com/vbpf/ebpf-verifier/files/8901257/timeout-0a4aa25126bf1edb3809bd6abf86616d81e2b2dc.zip)

**Comment by dthaler** [comment]
@Alan-Jowett was this fixed by PR #436?  Can this issue be closed now?

**Comment by Alan-Jowett** [comment]
This is fixed by this commit:
https://github.com/vbpf/ebpf-verifier/commit/25f3c24f6097bbde014a69ee69e51cbc5894cd50
