### ISSUE TITLE
Simplify the management of thread_local based state

### ISSUE THREAD

**Issue by Alan-Jowett** [vbpf/ebpf-verifier#458]
The ebpf-verifier currently stores a variety of state in various different thread_local variables, which makes it difficult to reliably clean up after verification. For cases where the verifier is used in a multi-threaded background daemon serving verification requests, the result is that there end up being multiple threads all containing thread local state that is infrequently used.

Proposal:
Wrap all the thread_local state in a single top-level structure that is then wrapped in a std::optional thread_local. 

Provide an API for callers to then release all the thread_local state via a reset of the single thread_local variable.

**Comment by Alan-Jowett** [comment]
Note: I am planning on working on this, but it looks like I can't assign this issue to myself.

**Comment by elazarg** [comment]
Sounds like a good idea.
