### ISSUE TITLE
Verification failure with no context or way to debug

### ISSUE THREAD

**Issue by Alan-Jowett** [vbpf/ebpf-verifier#463]
E:\ebpf-for-windows-demo\x64\Debug>\ebpf-for-windows-demo\packages\eBPF-for-Windows.0.6.0\build\native\bin\bpf2c.exe --bpf conn_track.o
```
Verification failed for sockops with error Verification failed
 Report:

exit: CRAB ERROR: Integer overflow during addition
```

I would recommend enhancing the CRAB ERROR report with more information so that the developer can know what instruction / line number is triggering this failure.

**Comment by dthaler** [comment]
https://github.com/vbpf/ebpf-verifier/pull/471 might have fixed this, does this still repro?

**Comment by dthaler** [comment]
Verified this is now fixed.  @elazarg it should be ok to close this issue now.
