### ISSUE TITLE
Prevail incorrectly classifying map as non-map - Cannot subtract pointers to non-singleton regions

### ISSUE THREAD

**Issue by Alan-Jowett** [vbpf/ebpf-verifier#502]
[map_repro.c.txt](https://github.com/vbpf/ebpf-verifier/files/11669711/map_repro.c.txt)

The problem appears to be this line:
```
    if (map == (void*)&ARRAY_map) {
        return 0;
    }
```

Where typeof map is void* and typeof ARRAY_map is an anonymous struct.

**Comment by dthaler** [comment]
There is no bug or "incorrect classifying".  The issue was that map_fd type was considered non-comparable, so this was just lack of a feature to support the sort of code quoted in the PR description.  It would fail verification rather than passing.
