### ISSUE TITLE
BTF type data with cycles should be rejected

### ISSUE THREAD

**Issue by Alan-Jowett** [vbpf/ebpf-verifier#506]
Malformed BTF data can contain cycles, which will cause issues computing type size and printing BTF type data.

It is better to reject malformed BTF data early on with a clearer error message.

**Comment by dthaler** [comment]
This bug still repros, please reopen

**Comment by dthaler** [comment]
Latest repro is because "visited" in PR #507 is always empty.

**Comment by dthaler** [comment]
@elazarg I believe this was fixed in #511, so this can be closed now
