### ISSUE TITLE
Unsafe XDP program passes verification on Windows

### ISSUE THREAD

**Issue by saxena-anurag** [vbpf/ebpf-verifier#560]
`xdp_md` struct fields (specifically `data` and `data_end`) have different sizes on Linux and Windows:

**Linux**:

```
struct xdp_md {
	__u32 data;
	__u32 data_end;
	__u32 data_meta;
	/* Below access go through struct xdp_rxq_info */
	__u32 ingress_ifindex; /* rxq->dev->ifindex */
	__u32 rx_queue_index;  /* rxq->queue_index  */
	__u32 egress_ifindex;  /* txq->dev->ifindex */
};
```

**Windows**:

```
typedef struct xdp_md_
{
    void* data;               ///< Pointer to start of packet data.
    void* data_end;           ///< Pointer to end of packet data.
    uint64_t data_meta;       ///< Packet metadata.
    uint32_t ingress_ifindex; ///< Ingress interface index.

    /* size: 26, cachelines: 1, members: 4 */
    /* last cacheline: 26 bytes */
} xdp_md_t;
```

`data` and `data_end` are 32-bit in Linux, but 64 bit in Windows.

A sample eBPF program **like below** (using asm code) passes verification on both Linux and Windows but crashes on Windows. The ASM code in the below program is truncating a 64-bit pointer to 32-bit, which is eventually causing a crash.

```
inline void *
data_start(xdp_md_t *ctx)
{
	void *ptr;
	asm volatile("%0 = *(u32 *)(%1 + %2)"
        : "=r"(ptr) : "r"(ctx), "i"(__builtin_offsetof(xdp_md_t, data)));
	return ptr;
}

SEC("xdp/unsafe")
int
unsafe_program(xdp_md_t* ctx)
{

    int rc = XDP_PASS;

    ETHERNET_HEADER* ethernet_header = NULL;
    char* next_header = data_start(ctx);           // <== 64-bit truncated to 32-bit.
    if (next_header + sizeof(ETHERNET_HEADER) > (char*)ctx->data_end) {
        goto Done;
    }

    ethernet_header = (ETHERNET_HEADER*)next_header;
    next_header = (char*)(ethernet_header + 1);
    if (ethernet_header->Type != ntohs(ETHERNET_TYPE_IPV4) && ethernet_header->Type != ntohs(ETHERNET_TYPE_IPV6)) {
        rc = XDP_DROP;
    }

Done:
    return rc;
}
```

**Comment by dthaler** [comment]
I don't think there is any verifier bug here.  Most likely there is a bug in bf2c.
See https://github.com/xdp-project/xdp-tutorial/blob/master/packet01-parsing/README.org#the-data-and-data_end-pointers but briefly (as summarized by Bing Chat):

> The data and data_end fields in the xdp_md struct are indeed defined as u32[\[1\]](https://mejedi.dev/posts/ebpf-dereference-of-modified-ctx-ptr-disallowed/). This might seem counterintuitive given that pointers are 64-bits wide in the BPF VM[\[2\]](https://github.com/xdp-project/xdp-tutorial/blob/master/packet01-parsing/README.org). The reason for this is related to the way BPF and XDP handle packet data.

> 
> In the context of BPF and XDP, data and data_end are not traditional pointers. Instead, they are offsets from the start of the packet data[\[2\]](https://github.com/xdp-project/xdp-tutorial/blob/master/packet01-parsing/README.org). These offsets are relative to a base address that is not directly accessible in the BPF program[\[2\]](https://github.com/xdp-project/xdp-tutorial/blob/master/packet01-parsing/README.org). This design choice is part of the security and safety features of BPF, as it prevents arbitrary memory access[\[2\]](https://github.com/xdp-project/xdp-tutorial/blob/master/packet01-parsing/README.org).

> 
> When the BPF program runs, it calculates the actual addresses by adding these offsets to the base address[\[2\]](https://github.com/xdp-project/xdp-tutorial/blob/master/packet01-parsing/README.org). This calculation is done in 64 bits, which is why the effective pointer size in BPF is 64 bits[\[2\]](https://github.com/xdp-project/xdp-tutorial/blob/master/packet01-parsing/README.org).

> 
> So, while data and data_end are defined as 32-bit values, they are used in a context where the effective pointer size is 64 bits[\[2\]](https://github.com/xdp-project/xdp-tutorial/blob/master/packet01-parsing/README.org). This is a unique aspect of BPF’s design and is part of what allows it to safely operate on packet data at the kernel level[\[2\]](https://github.com/xdp-project/xdp-tutorial/blob/master/packet01-parsing/README.org). For more detailed information, you may want to refer to the Linux Kernel documentation[\[2\]](https://github.com/xdp-project/xdp-tutorial/blob/master/packet01-parsing/README.org) or other relevant resources[\[1\]](https://mejedi.dev/posts/ebpf-dereference-of-modified-ctx-ptr-disallowed/).

**Comment by dthaler** [comment]
@saxena-anurag Ok, I am attempting a fix in the verifier that might work.  There did seem to be a validation bug which my PR will fix.

**Comment by dthaler** [comment]
@elazarg I believe this is fixed now and can be closed.
