### ISSUE TITLE
Why not implement the wrapped_interval domain to support machine integer analysis?

### ISSUE THREAD

**Issue by guangshengfan** [vbpf/ebpf-verifier#597]
The wrapped_interval  domain supports machine integer analysis, as showed in the paper "TOPLAS15-Interval Analysis and Machine Arithmetic: Why Signedness Ignorance Is Bliss". The PLDI'19 paper says PREVAIL is still built in mathematical integer and can not deal well with bitwise operations. So, Why not implement the wrapped_interval domain to support machine integer analysis? Besides, I see there are wrapped_interval domain calling in the 0.1-alpha's code.  Why not  continue to implement this domain in the later version of PREVAIL? I'm not very familiar to PREVAIL and eBPF.

**Comment by elazarg** [comment]
The wrapped-interval domain is non-relational. It does not track correlations between different variables. The Zones domain is much more precise in that respect.

It is possible to implement a "reduced product" of the two domains (and many others) to add precision, but I see no need for that; the current implementation handles bitwise operations with relatively good results in many cases.

If you have a concrete real-life example you need to handle, we will be happy to see it, and maybe add it to the ebpf samples repository. With enough such examples, we will try to find a solution, that may or may not involve adding a new numerical domain.

**Comment by guangshengfan** [comment]
Thank you for your reply!
