### ISSUE TITLE
libboost installation under Ubuntu

### ISSUE THREAD

**Issue by pchaigno** [vbpf/ebpf-verifier#78]
The installation steps described in the README fail with Ubuntu 18.04 because the version of libboost-dev in the Ubuntu repositories is too old:
```
src/main_check.cpp:6:10: fatal error: boost/container_hash/hash.hpp: No such file or directory
 #include <boost/container_hash/hash.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
`boost/container_hash/hash.hpp` was [introduced in version 1.67.0 of libboost](https://github.com/boostorg/container_hash/commit/53fbb04e88cf08138be207694a4accc3f9aaaac1#diff-19eec30efce3e5cbdf554e717e553663), the Ubuntu repositories have version 1.65:
```
$ apt-cache policy libboost-dev
libboost-dev:
  Installed: 1.65.1.0ubuntu1
  Candidate: 1.65.1.0ubuntu1
  Version table:
 *** 1.65.1.0ubuntu1 500
        500 http://fr.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
```

I managed to build the project after installing libboost 1.70.0 from sources as follows:
```
wget -q https://dl.bintray.com/boostorg/release/1.70.0/source/boost_1_70_0.tar.bz2
tar xvfo boost_1_70_0.tar.bz2
cd boost_1_70_0
./bootstrap.sh --with-libraries=atomic,chrono,context,coroutine,date_time,exception,filesystem,graph,graph_parallel,iostreams,locale,log,math,mpi,program_options,random,regex,serialization,system,test,thread,timer,wave
./b2 toolset=gcc cxxflags=-std=gnu++0x -j4
./b2 install
```

Do you prefer me to update the README with the installation-from-sources steps or using an alternative repository? Or maybe just specify the version of Ubuntu needed (18.10?)?

**Comment by caballa** [comment]
@elazar: can we change `boost/container_hash/hash.hpp` to `boost/functional/hash.hpp` ?

**Comment by elazarg** [comment]
Sure. I did that on the `submission` branch and somehow failed to port it to master.

**Comment by pchaigno** [comment]
On Ubuntu 18.04, the build now fails with:
```
In file included from /verifier/external/crab/include/crab/common/debug.hpp:5,
                 from /verifier/external/crab/lib/debug.cpp:1:
/verifier/external/crab/include/crab/common/os.hpp:4:10: fatal error: boost/shared_ptr.hpp: No such file or directory
 #include <boost/shared_ptr.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
I think the README should state the versions of libboost required. That would make it easier to reproduce on Ubuntu and elsewhere.

**Comment by elazarg** [comment]
> I think the README should state the versions of libboost required. That would make it easier to reproduce on Ubuntu and elsewhere.
You are right, of course. I didn't try it on 18.04 myself. Boost 1.67 should suffice, but I will verify.

> I also get that error for Ubuntu 18.10 with the libboost-dev from repositories.
This is strange. I used libboost-dev and it worked - it defaulted to 1.67. Specifically, `shared_ptr` is 1.63.

**Comment by pchaigno** [comment]
My bad. I had forgotten to add `libboost-dev` in the `apt-get install` line of my Dockerfile. Stupid mistake :s
