### ISSUE TITLE
Building with g++ : sorry, unimplemented: non-trivial designated initializers not supported

### ISSUE THREAD

**Issue by animeshtrivedi** [vbpf/ebpf-verifier#85]
Hi, 

Very cool work! On my Ubuntu 18.04 system if I compile with g++ (7 and 8) versions it complains 

```
build/asm_marshal.o <- src/asm_marshal.cpp
src/asm_marshal.cpp: In member function ‘std::vector<ebpf_inst> MarshalVisitor::makeLddw(Reg, bool, int32_t, int32_t)’:
src/asm_marshal.cpp:78:40: sorry, unimplemented: non-trivial designated initializers not supported
             ebpf_inst{ .imm = next_imm }
                                        ^
compilation terminated due to -Wfatal-errors.
Makefile:96: recipe for target 'build/asm_marshal.o' failed
make: *** [build/asm_marshal.o] Error 1
```
https://github.com/doslab/gcc-designated-initializer-support-cpp/wiki/GCC-Support-for-Non-trivial-designated-initializer-in-CPP

However, if I compile with `make CXX=clang++`, it works (as far as I can tell, need to do more testing).

**Comment by elazarg** [comment]
Thanks for reporting this!

This is surprising since nontrivial designated initializers are supported by g++-8. Does it work if you change the standard to `-std=c++2a`?

**Comment by animeshtrivedi** [comment]
Hmm, I think you are right. I tested on my second machine where g++-8 worked. May be it did not pick up before, the default g++ in Ubuntu is 7. Sorry for the confusion.  Also, `c++2a` works with `g++-8`.  

I will close the report ;)
